services:
  filebrowser:
    image: gtstef/filebrowser
    container_name: filebrowser-quantum
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml" # overrides the default path which is ./config.yaml
    #  FILEBROWSER_ADMIN_PASSWORD: "Admin2580!"
      TZ: "Asia/Seoul"
    # Non-Root
    #user: filebrowser
    volumes:
      - /DATA:/folder
      - ./data:/home/filebrowser/data
      - ./data/config.yaml:/home/filebrowser/data/config.yaml
    ports:
      - 28082:80
    restart: always
