services:
  db:
    image: mariadb:latest
    healthcheck:
      # 루트 비밀번호를 사용하여 정상적으로 DB 상태를 체크하도록 수정
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123 # 루트 비밀번호 설정
      - MYSQL_DATABASE=powerdnsadmin
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=mypdns
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - /APP/powerdns/pda-mysql:/var/lib/mysql

  pdns:
    image: pschiffe/pdns-mysql
    hostname: pdns
    domainname: computingforgeeks.com
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    # 줄바꿈 및 들여쓰기 오류 모두 수정됨
    environment:
      - PDNS_gmysql_host=db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=pdns
      - PDNS_gmysql_dbname=powerdnsadmin
      - PDNS_gmysql_password=mypdns
      - PDNS_api=yes
      - PDNS_api_key=itapiadmin2580!
      - PDNSCONF_API_KEY=itapiadmin2580!
      - PDNS_webserver=yes
      - PDNS_webserver_allow_from=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=Admin2580!
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_notify_from=0.0.0.0/0
      - PDNS_allow_axfr_ips=127.0.0.1

  web_app:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns_admin
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pdns:mypdns@db/powerdnsadmin
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
