services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://127.0.0.1:6875
      - APP_KEY=base64:bUsVgNL+PT57ZwKQ+nBcK3/dgWSMpg8hrCccxQcCt0M=
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USERNAME=bookstack
      - DB_PASSWORD=mysecretpassword
      - DB_DATABASE=bookstackapp
      - TZ=Asia/Seoul
      - APP_DEBUG=true
    volumes:
      - bookstack_app_data:/config 
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=mysecretpassword
    volumes:
      - bookstack_db_data:/config 
    restart: unless-stopped
volumes:
  bookstack_app_data: null
  bookstack_db_data: null
