services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'https://docmost.itapi.org'
      APP_SECRET: '16f5f227f90646fd245149a2ce0bd605194287dbb5cdf797c8477322925402bd'
      DATABASE_URL: 'postgresql://docmost:Admin2580!@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /APP/docmost:/app/data/storage

  db:
    image: postgres:18-alpine
    container_name: docmost-postgres
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: Admin2580!
    restart: unless-stopped
    volumes:
      - /APP/docmost/db_data:/var/lib/postgresql/data

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - /APP/docmost/redis_data:/data
